# Array Indexing

In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
x1=np.random.randint(10,size=10)

In [5]:
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [7]:
x1[0]

5

In [8]:
x1[9]=45

In [9]:
x1

array([ 5,  0,  3,  3,  7,  9,  3,  5,  2, 45])

In [10]:
x1[-1]

45

In [11]:
x1[-10]

5

In [12]:
x2=np.random.randint(10,size=(3,3))

In [13]:
x2

array([[7, 6, 8],
       [8, 1, 6],
       [7, 7, 8]])

In [14]:
x2[0,0]

7

In [16]:
x2[1,1]

1

In [17]:
x2[2,2]=54

In [18]:
x2

array([[ 7,  6,  8],
       [ 8,  1,  6],
       [ 7,  7, 54]])

In [19]:
x2[2,1]=56.89

In [20]:
x2

array([[ 7,  6,  8],
       [ 8,  1,  6],
       [ 7, 56, 54]])