# Array Slicing

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
x1=np.random.randint(10,size=10)

In [4]:
x2=np.random.randint(10,size=(4,4))

In [6]:
x1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [7]:
x1[0:5:1]

array([5, 0, 3, 3, 7])

In [8]:
x1[:4]

array([5, 0, 3, 3])

In [9]:
x1[4:9]

array([7, 9, 3, 5, 2])

In [10]:
x1[0::4]

array([5, 7, 2])

In [11]:
x1[::-4]

array([4, 9, 0])

In [12]:
x1[::-1]

array([4, 2, 5, 3, 9, 7, 3, 3, 0, 5])

In [14]:
x2

array([[7, 6, 8, 8],
       [1, 6, 7, 7],
       [8, 1, 5, 9],
       [8, 9, 4, 3]])

In [15]:
x2[0:2:1,0:2:1]

array([[7, 6],
       [1, 6]])

In [16]:
x2[:3,:3]

array([[7, 6, 8],
       [1, 6, 7],
       [8, 1, 5]])

In [17]:
x2[0,::]

array([7, 6, 8, 8])

In [18]:
x2[::,3]

array([8, 7, 9, 3])

In [19]:
x2[2]

array([8, 1, 5, 9])

In [20]:
x3=x2[:2,:2]

In [21]:
x3

array([[7, 6],
       [1, 6]])

In [22]:
x3[0,0]=78

In [23]:
x2

array([[78,  6,  8,  8],
       [ 1,  6,  7,  7],
       [ 8,  1,  5,  9],
       [ 8,  9,  4,  3]])

In [24]:
x4=x2[:3,:3].copy()

In [25]:
x4

array([[78,  6,  8],
       [ 1,  6,  7],
       [ 8,  1,  5]])

In [26]:
x4[2,2]=100

In [27]:
x4

array([[ 78,   6,   8],
       [  1,   6,   7],
       [  8,   1, 100]])

In [28]:
x2

array([[78,  6,  8,  8],
       [ 1,  6,  7,  7],
       [ 8,  1,  5,  9],
       [ 8,  9,  4,  3]])