# Creating array using numpy

In [16]:
import numpy as np

In [17]:
l=[1,2,3,4,5]

In [18]:
arr=np.array(l)

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
arr.dtype

dtype('int32')

In [21]:
l2=[1,1.2,3,5]

In [22]:
arr2=np.array(l2)

In [23]:
arr2

array([1. , 1.2, 3. , 5. ])

In [24]:
arr2.dtype

dtype('float64')

In [25]:
np.array([1,2,3,4,5],dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [26]:
l3=[[1,2,3],[15,16,17]]

In [27]:
np.array(l3)

array([[ 1,  2,  3],
       [15, 16, 17]])