# Random arrays

In [2]:
import numpy as np

## np.random.random()

In [3]:
np.random.random(10)

array([0.808921  , 0.79692807, 0.69884755, 0.56759716, 0.43038601,
       0.05410501, 0.49035707, 0.62771052, 0.78678602, 0.82903121])

## np.random.normal()

In [6]:
np.random.normal(5,1,10)

array([6.37750463, 5.83713115, 5.1169596 , 6.11352137, 3.53259094,
       5.54479257, 4.88802528, 3.73232656, 4.17638066, 6.12143799])

## np.random.randint()

In [7]:
np.random.randint(12,26,10)

array([19, 15, 23, 24, 25, 24, 18, 24, 25, 22])